### PR TITLE
Adding 2023 support to the mix

### PR DESCRIPTION
**Pull request by johnpierson**
Feel free to just cherry-pick changes. But I managed to get the projects added for Revit 2023 support.

The regular ZeroTouch nodes and UI nodes are now loading in Revit 2023 + Dynamo 2.13.x 

image

And a zipped version of the package for testing: (I think I did the version numbering correct)
[archi-lab.net.zip](https://github.com/ksobon/archilab/files/8541759/archi-lab.net.zip)

### CODE REVIEW

**Comment by ksobon** [comment]
@johnpierson wow! Thank you. I just received an email yesterday from a user that they wanted this done, and I put it on one of my TODO sticky notes. You beat me to it. Thank you!

**Comment by johnpierson** [comment]
Always glad to help out dude! 😁

**Comment by ksobon** [comment]
@johnpierson there are some issues here that I will be fixing and submitting a different PR. I don't want to "push" your hospitality and make you follow up with bunch of changes. You still get full credit for contributing the changes, they will get listed out as yours in the repo history. I just need to move it to a local branch so that I can work on it further. You can also see what I am changing if you are interested and we and we can discuss why if you want.

**Comment by johnpierson** [comment]
sounds good! I know there were a few API changes and some style stuff, so no worries at all!

**Comment by ksobon** [comment]
@johnpierson did you manually create the pkg.json file? I can't make it to take the new DLLs. The add file buttons throw up bunch of errors. Is it because the dlls that are already loaded into the bin folder get automatically loaded, so I have to remove them, open revit, then add them through the package manager interface? Is that what's happening here?

**Comment by johnpierson** [comment]
Oh. I manually did that as I wasn’t sure how else

**Comment by ksobon** [comment]
@johnpierson omg. That experience was horrible. So yeah, I had to put all of the dlls into the bin folder except two dlls that were meant to be node libraries. Then open up revit, dynamo, and go to manage pacakges, publish version, add files and load the two dlls. Check them off as node libraries, and then they get properly loaded as node libraries. Can't load all of the DLLs by selecting them as that makes all of them node libraries and then tries to add them into Dynamo as custom nodes. This interface is a major cluster f***.

**Pull request closed without merging**
